### ISSUE TITLE
Whatsapi.hasWhatsapp(JidProvider) is not wokring as expected

### ISSUE THREAD

**Issue by github-merusphere** [MsgCloudIn/Cobalt#1]
I am trying to use the Whatsapi.hasWhatsapp(JidProvider) function using WEB mode. 
The sample code as follows.

Jid jid = new Jid("918019016669", JidServer.WHATSAPP, 0, 0);
var  res = api.hasWhatsapp(jid).join();
System.out.println(jid.toPhoneNumber() + " :: " + res);

**Comment by github-merusphere** [comment]
I found that the code is tyring to using Contact/JidProvider to compare the Contact object send by the Whatsapi.hasWhatsapp(JidProvider) and Contacts in the Whatsapi.store(). The Comparison will fail because both objects are different. 

I have modified the code to consider the PhoneNumber for comparison.

commit ecbddc174c9280a3a5368676d8056284fff0a64a

**Comment by github-merusphere** [comment]
Tested and Closed

**Comment by pcvarma-sayukth** [comment]
Tested and Closed
