### ISSUE TITLE
Sending Audio an Video files Failed with an Error using mode::WEB

### ISSUE THREAD

**Issue by pcvarma-sayukth** [MsgCloudIn/Cobalt#3]
I have tried to send the Audio and Video files using the mode::WEB with the following code

// Audio
var audioImage = Files.readAllBytes(Path
	.of("/Users/pcvarma/Downloads/creepy.mp3"));
AudioMessage audio = new AudioMessageSimpleBuilder().media(audioImage)
	.voiceMessage(false).build();
api.sendMessage(contact, audio).join();

It failed with IOException

**Comment by pcvarma-sayukth** [comment]
We found that there is error while generating the Preview of the Audio and Video files. 
The code  Medias.getVideoThubnail(), generating an IOException, We have to catch it with Exception and return Optional.empty().

Made the changes the tested it is working fine.

commit 16cdd9866aaa352215920119257757f169ee471c

**Comment by github-merusphere** [comment]
Tested
